# Generated by Django 2.2.14 on 2020-07-03 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address])),
                ('phrase', models.CharField(max_length=1000)),
                ('result_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('query_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.QueryResult')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000, validators=[django.core.validators.URLValidator])),
                ('position', models.PositiveIntegerField()),
                ('query_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queries.QueryResult')),
            ],
        ),
    ]
