# Generated by Django 2.2.14 on 2020-07-05 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_popularword_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='user_browser',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
