# Generated by Django 2.2.14 on 2020-07-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20200705_1701'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='queryresult',
            index=models.Index(fields=['user_ip', 'user_browser', 'phrase'], name='queries_que_user_ip_a24921_idx'),
        ),
    ]
